# Generated by Django 5.1.1 on 2024-11-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('razao_social', models.CharField(blank=True, max_length=150, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
                ('plano', models.IntegerField(choices=[(0, 'Nenhum'), (1, 'Grátis'), (2, 'Mensal'), (3, 'Anual')], default=0)),
                ('consultas_restantes', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_farmacia', models.CharField(max_length=255)),
                ('product_url', models.URLField(max_length=1024)),
                ('ean', models.CharField(max_length=13)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_old', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('substance', models.CharField(blank=True, max_length=255, null=True)),
                ('factory', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('ean', 'nome_farmacia')},
            },
        ),
    ]
