# Generated by Django 5.1.1 on 2024-11-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastromodel',
            name='nome',
        ),
        migrations.AddField(
            model_name='cadastromodel',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cadastromodel',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cadastromodel',
            name='razao_social',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cadastromodel',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
