# Generated by Django 5.1.1 on 2024-11-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cadastromodel_nome_cadastromodel_cnpj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='razao_social',
        ),
    ]
