# Generated by Django 5.1.1 on 2024-11-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_nome_cliente_razao_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastromodel',
            name='cnpj',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cadastromodel',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
